# Generated by Django 4.0.1 on 2022-02-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_evento_usuario_alter_evento_data_criação_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='hora_criacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Hora'),
        ),
    ]
